<?php
$images = [
    ['src' => 'assets/media/components/b-isotope/branding/1.png', 'alt' => 'foto', 'category' => 'logo'],
    ['src' => 'assets/media/components/b-isotope/branding/2.png', 'alt' => 'foto', 'category' => 'logo'],
    ['src' => 'assets/media/components/b-isotope/branding/3.png', 'alt' => 'foto', 'category' => 'logo'],
    ['src' => 'assets/media/components/b-isotope/branding/4.png', 'alt' => 'foto', 'category' => 'logo'],
    ['src' => 'assets/media/components/b-isotope/branding/5.png', 'alt' => 'foto', 'category' => 'logo'],
    ['src' => 'assets/media/components/b-isotope/branding/6.png', 'alt' => 'foto', 'category' => 'logo'],
    ['src' => 'assets/media/components/b-isotope/branding/7.png', 'alt' => 'foto', 'category' => 'logo'],
    ['src' => 'assets/media/components/b-isotope/branding/8.png', 'alt' => 'foto', 'category' => 'logo'],
    ['src' => 'assets/media/components/b-isotope/branding/9.png', 'alt' => 'foto', 'category' => 'logo'],
    ['src' => 'assets/media/components/b-isotope/branding/10.png', 'alt' => 'foto', 'category' => 'logo'],
    ['src' => 'assets/media/components/b-isotope/branding/11.png', 'alt' => 'foto', 'category' => 'logo'],
    ['src' => 'assets/media/components/b-isotope/websites/1.png', 'alt' => 'foto', 'category' => 'web'],
    ['src' => 'assets/media/components/b-isotope/websites/2.png', 'alt' => 'foto', 'category' => 'web'],
    ['src' => 'assets/media/components/b-isotope/websites/3.png', 'alt' => 'foto', 'category' => 'web'],
    ['src' => 'assets/media/components/b-isotope/websites/4.png', 'alt' => 'foto', 'category' => 'web'],
    ['src' => 'assets/media/components/b-isotope/websites/5.png', 'alt' => 'foto', 'category' => 'web'],
    ['src' => 'assets/media/components/b-isotope/websites/6.png', 'alt' => 'foto', 'category' => 'web'],
    ['src' => 'assets/media/components/b-isotope/graphics/1.png', 'alt' => 'foto', 'category' => 'marketing'],
    ['src' => 'assets/media/components/b-isotope/graphics/2.png', 'alt' => 'foto', 'category' => 'marketing'],
    ['src' => 'assets/media/components/b-isotope/graphics/3.png', 'alt' => 'foto', 'category' => 'marketing'],
    ['src' => 'assets/media/components/b-isotope/graphics/4.png', 'alt' => 'foto', 'category' => 'marketing'],
    ['src' => 'assets/media/components/b-isotope/graphics/5.png', 'alt' => 'foto', 'category' => 'marketing'],
    ['src' => 'assets/media/components/b-isotope/graphics/6.png', 'alt' => 'foto', 'category' => 'marketing'],
    ['src' => 'assets/media/components/b-isotope/graphics/7.png', 'alt' => 'foto', 'category' => 'marketing'],
    ['src' => 'assets/media/components/b-isotope/graphics/8.png', 'alt' => 'foto', 'category' => 'marketing'],
];
?>
